### ISSUE TITLE
no such file or directory utils.js.map

### ISSUE THREAD

**Issue by Muji86** [jf3096/json-typescript-mapper#11]
I'm trying to use this with Ionic 2 and it sounds all too simple to implement however when I try to run my app I get the below error:
Any ideas?

Error: Module build failed: Error: ENOENT: no such file or directory, open 'D:\my-app\node_modules\json-typescript-mapper\libs\utils.js.map'
    at Error (native)
    at Object.<anonymous> (http://localhost:8100/build/main.js:107175:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:93208:15)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:107418:32)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:7567:22)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:6389:21)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)

**Comment by sumeshpunakkal** [comment]
Having same issue with Ionic 2 app

**Comment by Muji86** [comment]
@sumeshpunakkal I managed to fix it by generating a .map file using uglify js

**Comment by Punleu** [comment]
Has anyone found the solution for this issue yet?

**Comment by clarkmcnally** [comment]
I am still seeing this issue with ionic app, anyone solve this?

**Comment by wallacemv** [comment]
C:\xxx\node_modules\json-typescript-mapper>uglifyjs lib/utils.js -o utils.js --source-map utils.map.js 
will generate utils.js and utils.map.js in json-typescript-mapper folder... copy these files into lib folder @clarkmcnally

**Comment by eltimmo** [comment]
Getting the same issue with Angular 4. 

ERROR in ./node_modules/json-typescript-mapper/libs/utils.ts
Module build failed: Error: C:\Development\web\node_modules\json-typescript-mapper\libs\utils.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Development\web\cccweb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Development\web\cccweb\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/json-typescript-mapper/index.js 3:14-37
 @ ./src/app/powermanagement/pm-data-service/pm-data.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by GeorgeL9** [comment]
what @wallacemv said worked for Ionic 2, with a slight correction to the command:
`uglifyjs libs/utils.js -o utils.js --source-map `
